---
- name: Restart Apache
  service:
    name: apache2
    state: restarted
  when: ansible_os_family == "Debian"

- name: Restart HTTPD
  service:
    name: httpd
    state: restarted
  when: ansible_os_family == "RedHat"

